version: "3.7"

networks:
  pq_net:

services:
  postgresql.db:
    image: postgres:11.2
    networks:
      - pq_net
    container_name: postgresql.db
    ports:
      - "5432:5432"
    environment:
      - DATABASE=reportserverdb
      - USER=hppoc
      - PASSWD=hppoc
      - POSTGRES_USER=hppoc
      - POSTGRES_PASSWORD=hppoc
    volumes:
      - ./sqlscripts:/scripts
      - pgdata:/var/lib/postgresql/data
    #command: psql -U $POSTGRES_USER -v dbname=$DATABASE -v user=$USER -v passwd=$PASSWD -f /scripts/createpg.sql;
volumes:
  pgdata: